### ISSUE TITLE
Unit Test of Base32 implementation

### ISSUE THREAD

**Issue by alisa101rs** [jetpack-io/typeid-go#2]
I am not sure, but could you please double check the correctness of base32 implementation? 

Both, my rust implementation and [this website](https://cryptii.com/pipes/crockford-base32) give me different result for 
`[00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f]` input. My `000g40r40m30e209185gr38e1w` vs this repo's `00041061050r3gg28a1c60t3gf`.

**Comment by ongteckwu** [comment]
My output for the test case in for the typescript implementation https://github.com/ongteckwu/typeid-ts matches this repo's.

**Comment by loreto** [comment]
@alisa101rs Thanks for reporting.

I ran two tests:
1. I tried the encoding using `ulid` (which uses the same alphabet), it matched
2. I tried the encoding using `go`s standard base32 library, but with the custom alphabet ... it did *not* match.

So there's a discrepancy between the two approaches. I'm doing some more testing to determine what should be the "right" way to encode typeids and will clarify the spec. I'll circle back.

**Comment by loreto** [comment]
OK, I did a bunch of testing, and I think the original implementation in this repo is still correct.

In particular the current implementation aligns the encoding of the typeid in an intuitive way with UUIDs. So that,
the typeid `prefix_00000000000000000000000001` corresponds to the UUID `00000000-0000-0000-0000-000000000001`. I added a test to check for that here: https://github.com/jetpack-io/typeid-go/blob/main/typeid_test.go#L100

Note that the standard base32 algorithm works in groups of 5 bytes, and therefore is subject to add padding at the end
of the byte array one is trying to decode. In our case though, we use an algorithm without padding that works byte by byte; to make the standard base32 algorithm work, padding would have to be added to the front of the array.
I added a test to validate that here: https://github.com/jetpack-io/typeid-go/blob/main/base32/base32_test.go#L11
