### ISSUE TITLE
implement the standard interfaces

### ISSUE THREAD

**Issue by Karitham** [jetpack-io/typeid-go#4]
Both the typed and untyped version should consider implementing `MarshalText` and `MarshalBinary`, probably as well as `Decoder` and `Valuer`.

Opening this issue because I'm not sure what the defaults should be; always marshalling to/from a prefix, or no prefix? Does it make sense to keep the prefix in the case of a database field?

**Comment by loreto** [comment]
I've gone ahead and implemented `MarshalText` in https://github.com/jetpack-io/opensource/pull/92

I'm going to open separate issues for `MarshalBinary` and for `Valuer` mainly because:
1. I'm not sure what the binary representation should be. I'd have to define that as part of the typeid spec before implementing.
2. Until we have a Postgres module that natively supports TypeIDs or similar, users might want some flexibility on how to encode typeids in their db (if the DB supports native UUID types, they might want to use that, otherwise they might want to use a string)

Re: `Decoder`, if we're talking about https://pkg.go.dev/encoding/gob#GobDecoder I'm not sure that's needed since `gob` will also use `MarshalBinary` once that's defined.

In fact, if you look at https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/time/time.go;l=1325 you'll see that
`time.Time` from the standard library is suggesting removing those implementations in favor of `MarshalBinary`

**Comment by loreto** [comment]
Ah, gotcha. We'll track Scanner in https://github.com/jetpack-io/typeid-go/issues/6 as well.

Closing this issue since we're going to implement `MarshalText` and I've already opened two new issues to track binary encoding, and SQL interfaces.
